### PR TITLE
windows docs make workspace if not there

### PR DESCRIPTION
**Pull request by dschonholtz**

### CODE REVIEW

**Comment by Pwuts** [comment]
Please fill out the PR submission form. Also, your changes to the docs are regressive. Closing as invalid.

**Comment by dschonholtz** [comment]
@Pwuts This directly helps one of the folks in benchmarks who is struggling with windows docs and fixes a bug in with the auto_gpt_workspace.
We do not have a PR submission form to my knowledge for this repo yet. 

It is on the list. 
This is for AutoGPTBenchmarks not the code Auto-GPT repo. Can you confirm that you thought you were looking at a Auto-GPT PR? 
Happy to chat about benchmarks and getting this repo to a better state with respect to PR acceptance if you want.

**Comment by Pwuts** [comment]
Sorry, my bad. It showed up in my feed and I didn't notice that it wasn't in the main `AutoGPT` repo. Will pay better attention next time.

**Comment by jonathansheets517** [comment]
All good. Thanks for your hardwork Pwuts. we know you're slammed =)

**Pull request merged**
