### PR TITLE
Advanced LLM Evaluation Implementation

### PR DESCRIPTION
**Pull request by SilenNaihin**
## PR Type:
Enhancement

## Background
- Rubric evals evaluates the response based on a rubric
- Reference evals evaluates the response based on an ideal response
- Question eval
- Custom template

Can generate

- A score (0 or 1)
- A spectrum (1-10)
- A percentage (0-100)

Also added a new challenge for planning
___
## PR Description:
This PR introduces an advanced language model (LLM) evaluation feature. It includes changes to the scoring system, allowing for more complex evaluation types, including percentage, scale, and binary scoring. It also introduces new prompts for the evaluation process, and updates the data types to accommodate these changes.

___
## PR Main Files Walkthrough:
-`agbenchmark/utils/challenge.py`: This file has been significantly modified to incorporate the new LLM evaluation system. The scoring method now takes a config parameter, and the LLM evaluation method has been updated to use the new prompts and scoring types. The get_scores method has also been updated to handle the new LLM evaluation.
-`agbenchmark/utils/prompts.py`: This is a new file that contains the prompts used in the LLM evaluation. It includes different prompts for different scoring types and templates.
-`agbenchmark/utils/data_types.py`: This file has been updated to include a new Eval class, which represents the evaluation type, scoring method, template, and examples. The Ground class has also been updated to include an Eval instance.
-`.env.example`: This file has been updated to include the OPENAI_API_KEY environment variable, which is used in the LLM evaluation.
-`pyproject.toml`: A new marker 'content_gen' has been added.

### CODE REVIEW

**Comment by coditamar** [comment]
/ask why should we have a few types of scoring?

**Comment by SilenNaihin** [comment]
/ask why should we have a few types of scoring?

**Comment by SilenNaihin** [comment]
/ask why should we have a few types of scoring?

**Comment by SilenNaihin** [comment]
/ask why should we have a few types of scoring?

**Comment by SilenNaihin** [comment]
/ask why should we have a few types of scoring?

**Comment by SilenNaihin** [comment]
/ask why should we have a few types of scoring?

**Pull request merged**
