### PR TITLE
Datetime naming for recorded evals

### PR DESCRIPTION
**Pull request by rihp**
i have yet to test this but it should work

### CODE REVIEW

**Comment by rihp** [comment]
image
Tested and saves in this format

**Comment by dschonholtz** [comment]
Testing this locally. Seems good. I'm mucking around with the Github CLI. Used GitLab in the past so it is a bit of a learning experience.
I might make change and push it up if that is ok with you that shows the eval in the filename.

**Comment by dschonholtz** [comment]
Testing this locally. Seems good. I'm mucking around with the Github CLI. Used GitLab in the past so it is a bit of a learning experience.
I might make change and push it up if that is ok with you that shows the eval in the filename.

**Comment by dschonholtz** [comment]
image

**Comment by dschonholtz** [comment]
This works and I can run it fine on my machine. I really would like to get the eval names in here. I made the suggestions here because I can't push changes directly to your branch. 
Let me know if you have questions but I'm pretty sure this should just work

**Comment by dschonholtz** [comment]
This ended up sliding in with your graphing work. 
I am closing it.

**Comment by Pwuts** [comment]
We can still review it; it's not impossible to fix it up and merge, and before the rebase I promised to take any necessary rebases of PRs upon myself.

**Pull request closed without merging**
